# Generated by Django 5.2.6 on 2025-09-12 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=20, unique=True, verbose_name='MovieID')),
                ('title', models.CharField(max_length=200, verbose_name='MovieTitle')),
                ('actor1_name', models.CharField(max_length=100, verbose_name='Actor1Name')),
                ('actor2_name', models.CharField(blank=True, max_length=100, verbose_name='Actor2Name')),
                ('director_name', models.CharField(max_length=100, verbose_name='DirectorName')),
                ('genre', models.CharField(choices=[('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Action', 'Action'), ('Drama', 'Drama'), ('Thriller', 'Thriller'), ('Sci-Fi', 'Sci-Fi'), ('Horror', 'Horror'), ('Animation', 'Animation'), ('Other', 'Other')], max_length=20, verbose_name='MovieGenre')),
                ('release_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2026)], verbose_name='ReleaseYear')),
            ],
            options={
                'ordering': ['-release_year', 'title'],
            },
        ),
    ]
